swagger: "2.0"
info:
  description: "Battery Backend"
  version: "1.0.0"
  title: "Battery Backend"
  termsOfService: ""

  license:
    name: "Apache 2.0"
    url: "http://www.apache.org/licenses/LICENSE-2.0.html"
basePath: "/api"
tags:
- name: "battery"
- name: "charge"
- name: "measure"
  description: "Charge for battery"
schemes:
- "http"
paths:
  /battery:
    post:
      tags:
      - "battery"
      summary: "Add a new battery to database"
      description: ""
      operationId: "addBattery"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Battery object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/Battery"
      responses:
        "400":
          description: "No data provided"
        "422":
          description: "Validation error"
    get:
      tags:
      - "battery"
      summary: "Get all Active batteries from database"
      responses:
        "200":
          description: "Success"
  /battery/all:
    get:
      tags:
      - "battery"
      summary: "Get all batteries from database"
      responses:
        "200":
          description: "Success"
          
  /battery/{batteryId}:
    get:
      tags:
      - "battery"
      summary: "Find battery by ID"
      description: "Returns a single battery"
      produces:
      - "application/json"
      parameters:
      - name: "batteryId"
        in: "path"
        description: "ID of battery to return"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "200":
          description: "successful operation"
          schema:
            $ref: "#/definitions/Battery"
        "404":
          description: "Battery not found"
    delete:
      tags:
      - "battery"
      summary: "Delete a battery"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "batteryId"
        in: "path"
        description: "Battery id to delete"
        required: true
        type: "integer"
        format: "int32"
      responses:
        "422":
          description: "Battery not found"
    patch:
      tags:
      - "battery"
      summary: "Update an existing battery"
      description: ""
      produces:
      - "application/json"
      parameters:
      - name: "batteryId"
        in: "path"
        description: "Battery id to update"
        required: true
        type: "integer"
        format: "int32"
      - in: "body"
        name: "body"
        description: "Pet object that needs to be added to the store"
        required: true
        schema:
          $ref: "#/definitions/Battery"
      responses:
        "422":
          description: "Battery not found"
  /battery/plugged:
    get:
      tags:
      - "battery"
      summary: "Get all plugged batteries from database"
      responses:
        "200":
          description: "Success"
          
  /charge:
    get:
      tags:
      - "charge"
      summary: "Get all charges"
      description: ""
      operationId: "charge_all"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
    post:
      tags:
        - "charge"
      summary: "Add new charge"
      description: ""
      operationId: "add_new_charge"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Charge object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/Charge"
      responses:
        "200":
          description: "Success"
        "422":
          description: "Battery not found or Last charge did not end"
  /charge/{charge_id}:
    get:
      tags:
      - "charge"
      parameters:
        - in: path
          required: true
          name: charge_id
          type: integer
      summary: "Get charge"
      description: ""
      operationId: "get_charge"
      produces:
      - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            $ref: "#/definitions/Charge"
        "400":
          description: "Charge could not be found"
          
  /charge/battery/{battery_id}:
    get:
      tags:
        - "charge"
      parameters:
        - in: path
          required: true
          name: battery_id
          type: integer
      summary: "Get all charges for battery"
      description: ""
      operationId: "get_charges_for_battery"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Success"
        "404":
          description: "Could not be found"
  /charge/end/{charge_id}:
    patch:
      tags:
        - "charge"
      parameters:
        - in: path
          required: true
          name: charge_id
          type: integer
      summary: "End charge"
      description: ""
      operationId: "end_charge"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Success"
        "400":
          description: "Charge could not be found"
        "422":
          description: "Charge already ended"
  /measure:
    get:
      tags:
        - "measure"
      responses:
        "200":
          description: "Success"
    post:
      tags: 
      - "measure"
      summary: "Add a single meaasure for Charge"
      consumes:
      - "application/json"
      produces:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "Battery object that needs to be added to the database"
        required: true
        schema:
          $ref: "#/definitions/ChargeMeasurement"
      responses:
        "400":
          description: "No data provided"
        "422":
          description: "Validation error"
  /measure/{charge_id}:
    get:
      tags:
        - "measure"
      parameters:
      - in: path
        required: true
        name: charge_id
        type: integer
      summary: "Get measures for Charge"
      produces:
        - "application/json"
      responses:
        "200":
          description: "Success"
          schema:
            type: object
            properties:
              success:
                type: boolean
              data:
                $ref: '#/definitions/ChargeMeasurement'
        "404":
          description: "Could not be found"
          schema:
            type: object
            properties:
              success:
                type: boolean
                example: false
              error:
                type: object
                properties:
                  message:
                    type: array
                    items:
                      type: string
                      example: "No id 5"

responses:
  successResponse:
    

definitions:
  Battery:
    type: "object"
    required:
    - "is_active"
    - "capacity"
    - "discharge_rate"
    - "no_of_cells"
    - "maintenance_voltage"
    - "full_charge_voltage"
    - "min_voltage"
    properties:
      id:
        type: "integer"
        format: "int32"
        readOnly: true
      is_active:
        type: "boolean"
        example: true
        
      capacity :
        type: "integer"
        format: "int32"
        example: 2000
      discharge_rate:
        type: "integer"
        format: "int32"
        example: 20
      no_of_cells:
        type: "integer"
        format: "int32"
        example: 6
      production_date:
        type: "string"
        example: "2015-09-03"
      first_usage_date:
        type: "string"
        example: "2015-09-03"
      company:
        type: "string"
        example: "doggie"
      model:
        type: "string"
        example: "TR2"
  
      maintenance_voltage:
        type: "number"
        format: "float"
        example: 3.8
      full_charge_voltage:
        type: "number"
        format: "int32"
        example: 4.2
      min_voltage:
        type: "number"
        format: "float"
        example: 3.1
      no_of_battery_cycles:
        type: "integer"
        format: "int32"
        example: 0
  Charge:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
        example: 2
      battery_id:
        type: "integer"
        format: "int64"
        example: 4
      charging_station_id:
        type: "integer"
        format: "int64"
        example: 1
      start_date:
        type: "string"
        format: "date-time"
      end_date:
        type: "string"
        format: "date-time"
      charge_type:
        type: "string"
        format: "enum"
      start_voltage:
        type: "number"
        format: "float"
        example: 12.2
      end_voltage:
        type: "number"
        format: "float"
        example: 14.4
  ChargeMeasurement:
    type: "object"
    required:
    - "charge_id"
    - "voltage"
    properties:
      id:
        type: "integer"
        format: "int64"
        readOnly: true
        example: 0
      charge_id:
        type: "integer"
        format: "int64"
        example: 1
      capacity:
        type: "integer"
        format: "int64"
        example: 2500
      voltage:
        type: "number"
        format: "float64"
        example: 4.4
      amps:
        type: "number"
        format: "float64"
        example: 2.1
      temperature:
        type: "number"
        format: "float64"
        example: 40.1
      timestamp:
        type: "string"
        format: "date-time"
