version: "3"
services:
  web:
    build: .
    ports:
      - "5000:5000"
    env_file: .env.debug
    environment:
      - FLASK_APP=app.py
      - FLASK_DEBUG=1
      - POSTGRES_HOST=db
    volumes:
      - .:/app
    command: flask run --host=0.0.0.0 
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env.debug
    expose:
      - 5432
  tests:
    build:
      context: .
    environment:
        - FLASK_DEBUG=1
        - PY_TEST=1
    command: python -m pytest -v