version: "3"
services:
  web:
    build:
      context: .
    expose:
      - 5000
    env_file: .env.prod
    command: gunicorn 'app:app' --bind 0.0.0.0:5000 -w 3
    depends_on:
      - db
  db:
    image: postgres:10
    env_file: .env.prod.db
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    depends_on:
      - web
volumes:
  postgres_data:
